name:                inspector
version:             "0.2"
homepage:            https://github.com/primetype/inspector#readme
license:             BSD3
author:              Nicolas Di Prima
maintainer:          nicolas@primetype.co.uk
copyright:           2017-2018 PrimeType Ltd
category:            Testing
extra-source-files:
- README.md
- LICENSE

dependencies:
  - base
  - basement
  - foundation
  - memory
  - cryptonite

default-extensions:
    - NoImplicitPrelude
    - TypeFamilies
    - DataKinds
    - OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
    - Inspector
    - Inspector.Parser
    - Inspector.Display
  other-modules:
    - Inspector.Method
    - Inspector.Dict
    - Inspector.Monad
    - Inspector.Report
    - Inspector.Export
    - Inspector.Export.Markdown
    - Inspector.Export.Types

executables:
  example:
    main:        Main.hs
    source-dirs: example/
    dependencies:
    - inspector
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
