name:                inspector
version:             "0.2"
homepage:            https://github.com/primetype/inspector#readme
license:             BSD3
author:              Nicolas Di Prima
maintainer:          nicolas@primetype.co.uk
copyright:           2017-2018 PrimeType Ltd
category:            Testing
extra-source-files:
- README.md
- LICENSE

dependencies:
  - base
  - basement >= 0.0.7
  - foundation >= 0.0.20
  - memory >= 0.14.15
  - cryptonite

default-extensions:
    - NoImplicitPrelude
    - TypeFamilies
    - DataKinds
    - OverloadedStrings

ghc-options:
    - -Wall
    - -Werror

library:
  source-dirs: src
  exposed-modules:
    - Inspector
  other-modules:
    - Inspector.Method
    - Inspector.Monad
#    - Inspector.Report
#    - Inspector.Export.Markdown
    - Inspector.Export.Rust
    - Inspector.Export.Types
    - Inspector.Export.RefFile
    - Inspector.Export.Diff
    - Inspector.Parser
    - Inspector.Builder
    - Inspector.TestVector.Key
    - Inspector.TestVector.Types
    - Inspector.TestVector.Value
    - Inspector.TestVector.TestVector
  dependencies:
    - cli

executables:
  example:
    main:        Main.hs
    source-dirs: example/
    dependencies:
    - inspector
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
